"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";

type Profile={fullName:string|null;phone:string|null;destination:string|null;service:string|null;applicationStatus:string}|null;
type Doc={id:number;filename:string;category:string;status:string;createdAt:string};
type Appointment={id:number;service:string;preferredDate:string|null;status:string;adminNote:string|null;createdAt:string};
type Notice={id:number;title:string;message:string;createdAt:string};

export function PortalClient({user,profile,docs,appointments,notifications,verifiedPhone,signOut}:{user:{name:string,email:string};profile:Profile;docs:Doc[];appointments:Appointment[];notifications:Notice[];verifiedPhone:string|null;signOut:string}){
 const [message,setMessage]=useState("");
 const [items,setItems]=useState(docs);
 const [bookings,setBookings]=useState(appointments);
 const [phone,setPhone]=useState(profile?.phone||verifiedPhone||"");
 const [phoneVerified,setPhoneVerified]=useState(verifiedPhone);
 const [codeSent,setCodeSent]=useState(false);
 const [code,setCode]=useState("");

 async function saveProfile(e:FormEvent<HTMLFormElement>){e.preventDefault();setMessage("Saving…");const payload=Object.fromEntries(new FormData(e.currentTarget).entries());const r=await fetch("/api/profile",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});setMessage(r.ok?"Profile updated successfully.":"Could not update profile.");}
 async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();setMessage("Uploading securely…");const form=e.currentTarget;const data=new FormData(form);const r=await fetch("/api/documents",{method:"POST",body:data});const out=await r.json();if(r.ok){setItems(x=>[out.document,...x]);setMessage("Document uploaded for review.");form.reset()}else setMessage(out.error||"Upload failed.");}
 async function requestAppointment(e:FormEvent<HTMLFormElement>){e.preventDefault();setMessage("Submitting appointment…");const form=e.currentTarget;const payload=Object.fromEntries(new FormData(form).entries());const r=await fetch("/api/appointments",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const out=await r.json();if(r.ok){setBookings(x=>[out.appointment,...x]);setMessage("Appointment request submitted.");form.reset()}else setMessage(out.error||"Could not request appointment.");}
 async function sendCode(){setMessage("Sending verification code…");const r=await fetch("/api/verification/phone",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"send",phone})});const out=await r.json();if(r.ok){setCodeSent(true);setMessage(out.previewCode?`Preview code: ${out.previewCode}`:"Verification code sent by SMS.")}else setMessage(out.error||"Could not send code.");}
 async function confirmCode(){setMessage("Checking code…");const r=await fetch("/api/verification/phone",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"confirm",phone,code})});const out=await r.json();if(r.ok){setPhoneVerified(out.phone);setCodeSent(false);setMessage("Mobile number verified successfully.")}else setMessage(out.error||"Verification failed.");}

 return <div className="dashboard-shell"><aside className="sidebar"><Link className="brand" href="/"><img className="brand-mark" src="/brand-logo.png" alt="IELTS World & SMART World Consultancy logo"/><span>Student Portal</span></Link><nav className="side-nav"><a href="#overview">▦ Dashboard</a><a href="#profile">○ My Profile</a><a href="#documents">▤ Documents</a><a href="#appointments">□ Appointments</a><a href="#notifications">◉ Notifications</a><a href={signOut}>↗ Sign out</a></nav></aside><main className="dash-main"><div className="dash-head"><div><span className="kicker">WELCOME BACK</span><h1>{user.name}</h1><p>{user.email}</p></div><Link className="btn btn-light" href="/">← Website</Link></div>
 <div id="overview" className="grid stats"><div className="stat"><span>Profile</span><strong>{profile?"70%":"20%"}</strong></div><div className="stat"><span>Documents</span><strong>{items.length}</strong></div><div className="stat"><span>Application</span><strong style={{fontSize:18}}>{profile?.applicationStatus||"Not started"}</strong></div><div className="stat"><span>Appointments</span><strong>{bookings.length}</strong></div></div>
 <div className="panel"><h3>Application progress</h3><div className="progress"><span/></div><p className="section-lead">Profile Created → Documents → Review → Application → Visa</p></div>
 {message&&<div className="notice portal-message" role="status">{message}</div>}
 <div className="grid portal-grid"><form id="profile" className="panel" onSubmit={saveProfile}><h3>Personal profile</h3><div className="field"><label htmlFor="profile-name">Full name</label><input id="profile-name" name="fullName" defaultValue={profile?.fullName||user.name}/></div><div className="field"><label htmlFor="profile-phone">Phone</label><input id="profile-phone" name="phone" value={phone} onChange={e=>setPhone(e.target.value)} required/></div><div className="field"><label htmlFor="profile-destination">Preferred destination</label><select id="profile-destination" name="destination" defaultValue={profile?.destination||"UK"}><option>UK</option><option>Canada</option><option>Australia</option><option>Japan</option><option>Korea</option><option>Malaysia</option></select></div><div className="field"><label htmlFor="profile-service">Service</label><select id="profile-service" name="service" defaultValue={profile?.service||"Study Abroad"}><option>Study Abroad</option><option>IELTS / PTE</option><option>Visa Guidance</option><option>Language Course</option></select></div><button className="btn btn-blue">Save profile</button></form>
 <section className="panel"><h3>Account verification</h3><div className="verified-line"><span>✓</span><div><strong>Email verified</strong><small>{user.email}</small></div></div><div className={`verified-line ${phoneVerified?"verified":""}`}><span>{phoneVerified?"✓":"○"}</span><div><strong>{phoneVerified?"Mobile verified":"Verify mobile number"}</strong><small>{phoneVerified||"A one-time code will be sent by SMS"}</small></div></div>{!phoneVerified&&<><div className="field"><label htmlFor="verification-phone">Bangladesh mobile number</label><input id="verification-phone" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="01XXXXXXXXX"/></div><button type="button" className="btn btn-blue" onClick={sendCode}>Send code</button>{codeSent&&<div className="verification-code"><input aria-label="Verification code" value={code} onChange={e=>setCode(e.target.value)} inputMode="numeric" placeholder="Verification code"/><button type="button" className="btn btn-primary" onClick={confirmCode}>Verify</button></div>}</>}</section>
 <form className="panel" onSubmit={upload}><h3>Secure document upload</h3><div className="notice">Files are private and visible only to you and authorised staff.</div><div className="field" style={{marginTop:15}}><label htmlFor="document-category">Document category</label><select id="document-category" name="category"><option>Passport</option><option>Academic Certificate</option><option>Transcript</option><option>Language Test Result</option><option>Bank Statement</option><option>CV / SOP</option><option>Other</option></select></div><div className="field"><label htmlFor="document-file">PDF, JPG or PNG · Max 8 MB</label><input id="document-file" name="file" type="file" accept=".pdf,.jpg,.jpeg,.png" required/></div><button className="btn btn-primary">Upload securely</button></form>
 <form id="appointments" className="panel" onSubmit={requestAppointment}><h3>Request appointment</h3><input type="hidden" name="name" value={profile?.fullName||user.name}/><input type="hidden" name="phone" value={phone}/><div className="field"><label htmlFor="appointment-service">Service</label><select id="appointment-service" name="service"><option>Free Counselling</option><option>Study Abroad</option><option>IELTS / PTE</option><option>Visa Guidance</option><option>Document Review</option></select></div><div className="field"><label htmlFor="appointment-date">Preferred date</label><input id="appointment-date" type="date" name="preferredDate"/></div><div className="field"><label htmlFor="appointment-message">Message</label><textarea id="appointment-message" name="message" placeholder="Tell us what you need help with"/></div><button className="btn btn-blue">Submit request</button></form></div>
 <section id="documents" className="panel"><h3>Your documents</h3><div className="doc-list">{items.length?items.map(d=><div className="doc" key={d.id}><span><strong>{d.category}</strong><small>{d.filename}</small></span><span className="doc-actions"><span className="status">{d.status}</span><a href={`/api/documents?id=${d.id}`} target="_blank" rel="noreferrer">Open</a></span></div>):<p className="section-lead">No documents uploaded yet.</p>}</div></section>
 <section className="panel"><h3>Your appointments</h3><div className="doc-list">{bookings.length?bookings.map(a=><div className="doc" key={a.id}><span><strong>{a.service}</strong><small>{a.preferredDate||"Flexible date"}{a.adminNote?` · ${a.adminNote}`:""}</small></span><span className="status">{a.status}</span></div>):<p className="section-lead">No appointment requested yet.</p>}</div></section>
 <section id="notifications" className="panel"><h3>Notifications</h3><div className="doc-list">{notifications.length?notifications.map(n=><div className="doc" key={n.id}><span><strong>{n.title}</strong><small>{n.message}</small></span><small>{new Date(n.createdAt).toLocaleDateString()}</small></div>):<p className="section-lead">No notifications yet.</p>}</div></section>
 </main></div>;
}
