"use client";

import Link from "next/link";
import { LanguageSwitcher, useSiteLanguage } from "../components/SiteLanguage";

export default function Terms() {
  const { language } = useSiteLanguage();
  const bn = language === "bn";
  return <main className="legal"><div className="legal-top"><Link className="brand" href="/"><img className="brand-mark" src="/brand-logo.png" alt="IELTS World & SMART World Consultancy logo"/><span>IELTS World & SMART World Consultancy</span></Link><LanguageSwitcher/></div><h1>{bn ? "সেবার শর্তাবলি" : "Terms of Service"}</h1><p>{bn ? "সর্বশেষ হালনাগাদ: ১৫ আগস্ট ২০২৬" : "Last updated: 15 August 2026"}</p><h2>{bn ? "পরামর্শসেবা" : "Consultancy service"}</h2><p>{bn ? "আমরা course, admission ও visa process-এ professional guidance প্রদান করি। University admission, scholarship বা visa decision সংশ্লিষ্ট কর্তৃপক্ষের; কোনো ফলাফল নিশ্চিত নয়।" : "We provide professional guidance for courses, admissions and visa processes. University admissions, scholarships and visa decisions are made by the relevant authorities; no outcome is guaranteed."}</p><h2>{bn ? "সঠিক তথ্য" : "Accurate information"}</h2><p>{bn ? "Client-কে সত্য, সম্পূর্ণ এবং বৈধ তথ্য ও documents দিতে হবে। ভুল বা জাল document-এর দায় client-এর এবং এমন service আমরা বাতিল করতে পারি।" : "Clients must provide truthful, complete and valid information and documents. The client is responsible for false or fraudulent documents, and we may cancel the related service."}</p><h2>{bn ? "ফি ও রিফান্ড" : "Fees and refunds"}</h2><p>{bn ? "প্রযোজ্য fee, third-party charge এবং refund condition service agreement বা receipt-এ উল্লেখ থাকবে। Payment করার আগে লিখিত terms যাচাই করুন।" : "Applicable fees, third-party charges and refund conditions will be stated in the service agreement or receipt. Review the written terms before making payment."}</p><h2>{bn ? "অ্যাকাউন্ট নিরাপত্তা" : "Account security"}</h2><p>{bn ? "নিজের account এবং documents গোপন রাখার দায়িত্ব ব্যবহারকারীর। সন্দেহজনক activity দেখলে দ্রুত আমাদের জানান।" : "Users are responsible for keeping their accounts and documents confidential. Notify us promptly if you notice suspicious activity."}</p><Link className="btn btn-blue" href="/">← {bn ? "হোম" : "Home"}</Link></main>;
}
