export type CourseDetailContent = {
  cardDescriptionBn?: string; tagsBn?: string;
  subtitle: string; subtitleBn: string; overview: string; overviewBn: string;
  duration: string; schedule: string; level: string; fee: string;
  modules: string; modulesBn: string; outcomes: string; outcomesBn: string;
  requirements: string; requirementsBn: string;
};

const sharedRequirements = {
  requirements: "A commitment to attend classes, complete practice tasks and participate in progress assessments. No previous test score is required unless stated during counselling.",
  requirementsBn: "নিয়মিত ক্লাসে উপস্থিতি, অনুশীলনের কাজ সম্পন্ন করা এবং অগ্রগতি যাচাইয়ে অংশ নেওয়ার মানসিকতা। কাউন্সেলিংয়ে আলাদাভাবে বলা না হলে আগের কোনো পরীক্ষার স্কোর প্রয়োজন নেই।",
};

export const genericCourseDetail: CourseDetailContent = {
  cardDescriptionBn:"পরিকল্পিত ক্লাস, ব্যবহারিক অনুশীলন এবং ব্যক্তিগত ফিডব্যাকসহ একটি পূর্ণাঙ্গ কোর্স।", tagsBn:"নিয়মিত · সাপ্তাহিক ছুটি",
  subtitle: "Structured learning, guided practice and measurable progress.",
  subtitleBn: "পরিকল্পিত শেখা, গাইডেড অনুশীলন এবং পরিমাপযোগ্য অগ্রগতি।",
  overview: "This professionally structured course combines instructor-led lessons, practical exercises, feedback and progress checks to help learners reach a clear academic or career goal.",
  overviewBn: "এই পেশাদারভাবে পরিকল্পিত কোর্সে প্রশিক্ষকের ক্লাস, ব্যবহারিক অনুশীলন, ব্যক্তিগত ফিডব্যাক ও অগ্রগতি যাচাইয়ের মাধ্যমে শিক্ষার্থীদের নির্দিষ্ট শিক্ষা বা ক্যারিয়ারের লক্ষ্যে পৌঁছাতে সহায়তা করা হয়।",
  duration: "Flexible programme", schedule: "Regular & weekend batches", level: "All suitable levels", fee: "Contact for current fee",
  modules: "Foundation assessment\nCore skills development\nGuided practice\nProgress tests\nFinal preparation",
  modulesBn: "প্রাথমিক দক্ষতা যাচাই\nমূল দক্ষতা উন্নয়ন\nগাইডেড অনুশীলন\nঅগ্রগতি পরীক্ষা\nচূড়ান্ত প্রস্তুতি",
  outcomes: "Build practical confidence\nUnderstand the course framework\nImprove through targeted feedback\nReceive a clear next-step plan",
  outcomesBn: "ব্যবহারিক আত্মবিশ্বাস তৈরি\nকোর্সের কাঠামো বোঝা\nলক্ষ্যভিত্তিক ফিডব্যাকে উন্নতি\nপরবর্তী ধাপের পরিষ্কার পরিকল্পনা পাওয়া",
  ...sharedRequirements,
};

export const defaultCourseDetails: Record<string, CourseDetailContent> = {
  "IELTS Preparation": { cardDescriptionBn:"Academic ও General—চারটি মডিউলের পূর্ণাঙ্গ প্রস্তুতি, মক টেস্ট এবং ব্যক্তিগত ফিডব্যাক।",tagsBn:"নিয়মিত · সাপ্তাহিক ছুটি", subtitle:"A complete Academic and General IELTS pathway built around your target band.", subtitleBn:"আপনার লক্ষ্য ব্যান্ড অনুযায়ী Academic ও General IELTS-এর পূর্ণাঙ্গ প্রস্তুতি।", overview:"Develop Listening, Reading, Writing and Speaking through a diagnostic-led study plan, trainer feedback, timed practice and full mock tests. The course focuses on both test strategy and the English skills needed for a confident performance.", overviewBn:"Diagnostic test-ভিত্তিক study plan, trainer feedback, সময়ভিত্তিক practice ও পূর্ণাঙ্গ mock test-এর মাধ্যমে Listening, Reading, Writing ও Speaking দক্ষতা উন্নয়ন করা হয়। পরীক্ষার কৌশলের পাশাপাশি আত্মবিশ্বাসী ফলাফলের জন্য প্রয়োজনীয় ইংরেজি দক্ষতায় গুরুত্ব দেওয়া হয়।", duration:"8–12 weeks", schedule:"Regular & weekend batches", level:"Foundation to advanced", fee:"Contact for current fee", modules:"IELTS format & diagnostic test\nListening strategies\nAcademic reading skills\nWriting Task 1 & Task 2\nSpeaking fluency & mock interviews\nFull-length mock tests", modulesBn:"IELTS format ও diagnostic test\nListening কৌশল\nAcademic reading দক্ষতা\nWriting Task 1 ও Task 2\nSpeaking fluency ও mock interview\nপূর্ণাঙ্গ mock test", outcomes:"Use proven strategies across all four modules\nWrite structured, relevant responses\nSpeak with greater fluency and confidence\nTrack readiness through scored mock tests", outcomesBn:"চারটি module-এ কার্যকর কৌশল ব্যবহার\nগঠিত ও প্রাসঙ্গিক উত্তর লেখা\nআরও সাবলীল ও আত্মবিশ্বাসের সঙ্গে কথা বলা\nস্কোরকৃত mock test-এ প্রস্তুতি যাচাই", ...sharedRequirements },
  "PTE Academic": { subtitle:"Technology-supported PTE preparation for faster, focused score improvement.", subtitleBn:"দ্রুত ও লক্ষ্যভিত্তিক স্কোর উন্নয়নের জন্য প্রযুক্তিনির্ভর PTE প্রস্তুতি।", overview:"Learn the PTE task formats, scoring priorities and time-management strategies through AI-scored practice, instructor review and repeated simulations of the real computer-based test.", overviewBn:"AI-scored practice, instructor review ও বাস্তব computer-based পরীক্ষার simulation-এর মাধ্যমে PTE task format, scoring priority এবং time management কৌশল শেখানো হয়।", duration:"6–10 weeks", schedule:"Regular, intensive & weekend", level:"Intermediate and above", fee:"Contact for current fee", modules:"PTE test orientation\nSpeaking & pronunciation\nWriting templates and accuracy\nReading strategies\nListening and note-taking\nAI-scored mocks", modulesBn:"PTE test পরিচিতি\nSpeaking ও pronunciation\nWriting template ও accuracy\nReading কৌশল\nListening ও note-taking\nAI-scored mock", outcomes:"Understand PTE scoring\nRespond accurately under time pressure\nImprove speaking delivery\nUse mock analytics to target weak areas", outcomesBn:"PTE scoring বোঝা\nসময়চাপের মধ্যে সঠিক উত্তর দেওয়া\nSpeaking delivery উন্নত করা\nMock analytics দিয়ে দুর্বলতা চিহ্নিত করা", ...sharedRequirements },
  "OIETC / ELLT": { subtitle:"Focused Oxford ELLT preparation for UK university admission pathways.", subtitleBn:"UK university admission pathway-এর জন্য লক্ষ্যভিত্তিক Oxford ELLT প্রস্তুতি।", overview:"Prepare for Oxford ELLT language assessment components with guided skills lessons, interview practice, academic writing support and admission-focused counselling.", overviewBn:"Guided skill lesson, interview practice, academic writing support ও admission counselling-এর মাধ্যমে Oxford ELLT language assessment-এর সব অংশের প্রস্তুতি দেওয়া হয়।", duration:"6–8 weeks", schedule:"Regular & flexible batches", level:"A1 to advanced", fee:"Contact for current fee", modules:"Assessment orientation\nReading and listening\nAcademic writing\nSpeaking interview\nPractice assessments\nApplication guidance", modulesBn:"Assessment পরিচিতি\nReading ও listening\nAcademic writing\nSpeaking interview\nPractice assessment\nApplication guidance", outcomes:"Understand each assessment stage\nCommunicate confidently in the interview\nProduce clearer academic writing\nPrepare an admission-ready pathway", outcomesBn:"Assessment-এর প্রতিটি ধাপ বোঝা\nInterview-এ আত্মবিশ্বাসের সঙ্গে কথা বলা\nপরিষ্কার academic writing তৈরি\nভর্তির জন্য প্রস্তুত pathway তৈরি", ...sharedRequirements },
  "Spoken English": { subtitle:"Practical English for confident everyday, academic and professional communication.", subtitleBn:"দৈনন্দিন, শিক্ষা ও পেশাগত যোগাযোগে আত্মবিশ্বাসের জন্য ব্যবহারিক ইংরেজি।", overview:"Build speaking confidence through conversation practice, pronunciation coaching, useful grammar, vocabulary development, presentations and realistic communication scenarios.", overviewBn:"Conversation practice, pronunciation coaching, প্রয়োজনীয় grammar, vocabulary, presentation ও বাস্তব যোগাযোগের পরিস্থিতির মাধ্যমে speaking confidence তৈরি করা হয়।", duration:"8–12 weeks", schedule:"Regular & weekend batches", level:"Beginner to advanced", fee:"Contact for current fee", modules:"Everyday conversation\nPronunciation and clarity\nPractical grammar\nVocabulary building\nPresentation skills\nInterview communication", modulesBn:"দৈনন্দিন conversation\nPronunciation ও clarity\nব্যবহারিক grammar\nVocabulary building\nPresentation skill\nInterview communication", outcomes:"Speak more naturally\nUse accurate everyday English\nPresent ideas with confidence\nHandle interviews and workplace conversations", outcomesBn:"আরও স্বাভাবিকভাবে কথা বলা\nসঠিক দৈনন্দিন ইংরেজি ব্যবহার\nআত্মবিশ্বাসের সঙ্গে ধারণা উপস্থাপন\nInterview ও workplace conversation পরিচালনা", ...sharedRequirements },
  "Japanese Language": { subtitle:"A structured N5–N4 foundation for study, work and life in Japan.", subtitleBn:"জাপানে পড়াশোনা, কাজ ও জীবনের জন্য পরিকল্পিত N5–N4 ভিত্তি।", overview:"Learn scripts, grammar, vocabulary, listening and practical conversation with JLPT-oriented milestones and cultural guidance for students planning a future in Japan.", overviewBn:"জাপানে ভবিষ্যৎ পরিকল্পনাকারীদের জন্য JLPT-ভিত্তিক milestone ও cultural guidance-এর সঙ্গে script, grammar, vocabulary, listening ও practical conversation শেখানো হয়।", duration:"4–8 months", schedule:"Regular & weekend batches", level:"N5 to N4", fee:"Contact for current fee", modules:"Hiragana & Katakana\nCore grammar\nDaily vocabulary\nListening practice\nPractical conversation\nJLPT preparation", modulesBn:"Hiragana ও Katakana\nমূল grammar\nদৈনন্দিন vocabulary\nListening practice\nPractical conversation\nJLPT preparation", outcomes:"Read and write basic Japanese\nHandle everyday conversations\nBuild an N5–N4 vocabulary base\nPrepare for further JLPT study", outcomesBn:"মৌলিক Japanese পড়া ও লেখা\nদৈনন্দিন conversation পরিচালনা\nN5–N4 vocabulary base তৈরি\nপরবর্তী JLPT study-এর প্রস্তুতি", ...sharedRequirements },
  "Korean Language": { subtitle:"Korean language skills for communication, study and future work pathways.", subtitleBn:"যোগাযোগ, পড়াশোনা ও ভবিষ্যৎ কর্মপথের জন্য Korean language skills।", overview:"Develop Hangul literacy, essential grammar, vocabulary, listening and real-life conversation through a progressive course suitable for beginners and pathway-focused learners.", overviewBn:"Beginner ও pathway-focused শিক্ষার্থীদের জন্য ধাপে ধাপে Hangul, প্রয়োজনীয় grammar, vocabulary, listening ও বাস্তব conversation শেখানো হয়।", duration:"3–6 months", schedule:"Regular & weekend batches", level:"Beginner to pathway preparation", fee:"Contact for current fee", modules:"Hangul reading & writing\nEssential grammar\nEveryday vocabulary\nListening practice\nSpeaking situations\nPathway orientation", modulesBn:"Hangul পড়া ও লেখা\nপ্রয়োজনীয় grammar\nদৈনন্দিন vocabulary\nListening practice\nSpeaking situations\nPathway orientation", outcomes:"Read and write Hangul\nUse basic Korean confidently\nUnderstand common conversations\nPrepare for advanced or pathway study", outcomesBn:"Hangul পড়া ও লেখা\nআত্মবিশ্বাসের সঙ্গে basic Korean ব্যবহার\nসাধারণ conversation বোঝা\nAdvanced বা pathway study-এর প্রস্তুতি", ...sharedRequirements },
};

export const banglaCourseCards:Record<string,{cardDescriptionBn:string;tagsBn:string}> = {
  "IELTS Preparation":{cardDescriptionBn:"Academic ও General—চারটি মডিউলের পূর্ণাঙ্গ প্রস্তুতি, মক টেস্ট এবং ব্যক্তিগত ফিডব্যাক।",tagsBn:"নিয়মিত · সাপ্তাহিক ছুটি"},
  "PTE Academic":{cardDescriptionBn:"AI-ভিত্তিক অনুশীলন, পরীক্ষার কৌশল এবং দ্রুত স্কোর উন্নয়নের নিবিড় কোর্স।",tagsBn:"প্র্যাকটিস ল্যাব · মক"},
  "OIETC / ELLT":{cardDescriptionBn:"UK-তে ভর্তির জন্য Oxford International English Test প্রস্তুতি ও আবেদন গাইডেন্স।",tagsBn:"A1 থেকে Advanced"},
  "Spoken English":{cardDescriptionBn:"দৈনন্দিন ও পেশাগত যোগাযোগে আত্মবিশ্বাস তৈরির ব্যবহারিক কোর্স।",tagsBn:"Beginner · Advanced"},
  "Japanese Language":{cardDescriptionBn:"জাপানে পড়াশোনা ও ক্যারিয়ারের লক্ষ্য নিয়ে N5–N4 ভিত্তিক ভাষা প্রশিক্ষণ।",tagsBn:"N5 · N4"},
  "Korean Language":{cardDescriptionBn:"ভবিষ্যৎ পড়াশোনা ও কাজের জন্য পরিকল্পিত কোরিয়ান ভাষা কোর্স।",tagsBn:"Beginner · EPS"},
};

export function courseDetailFor(title: string) {
  return { ...genericCourseDetail, ...(defaultCourseDetails[title] || {}), ...(banglaCourseCards[title] || {}) };
}
